os:
  - linux

language: php

php:
  - '7.4'
  
before_script:
  - npm install
  - composer self-update
  - composer install --no-interaction
  - composer update
  - php artisan key:generate
  
script:
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit

