version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: /var/www/html/build.sh
      runas: root
  ApplicationStart:
    - location: php artisan serve
      runas: root


